version : '3.7'
networks:
  hy-net:
    external: true
services:
  igs:
        container_name : igs
        hostname: igs
        networks:
          hy-net:
        image: registry.cn-hangzhou.aliyuncs.com/trsrd/tomat:9.0.0-igs-jdk1.8
        volumes:
           - /TRS/HyCloud/IGS/logs:/TRS/HyCloud/IGS/logs
           - /TRS/HyCloud/IGS/webapps:/TRS/HyCloud/IGS/webapps
        restart: on-failure
        environment:
          TZ: Asia/Shanghai
          JAVA_OPTS : "-server -Xms1024m -Xmx1024M -Djava,security.egd=file:/dev/.urandom -Dfile.encoding=utf-8 -Xloggc:/TRS/HyCloud/IGS/logs/gc.log -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=9877"
        ports :
                - 8082:8080
#                - 9877:9877
        ulimits: #/etc/sysctl.conf   vm.max_map_count=262144
          memlock:
            soft: -1
            hard: -1
          nproc: 65535
          nofile:
            soft: 65535
            hard: 65535
